rm -rf build
mkdir build && cd build
cmake   -DCMAKE_SYSTEM_NAME=Linux \
	-DCMAKE_SYSTEM_VERSION=1 \
	-DMNN_BUILD_HARD=OFF \
	-DMNN_BUILD_SHARED_LIBS=ON \
	-DMNN_FORBID_MULTI_THREAD=ON \
	-DMNN_BUILD_MINI=OFF \
	-DMNN_BUILD_CONVERTER=ON \
	-DMNN_LOW_MEMORY=ON \
	-DCMAKE_BUILD_TYPE=Release \
	-DMNN_BUILD_QUANTOOLS=OFF  \
	..

make -j20
